import os

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Enables error emails.
CELERY_SEND_TASK_ERROR_EMAILS = True
CELERY_WORKER_DISABLE_RATE_LIMITS = True
CELERY_WORKER_HIJACK_ROOT_LOGGER = False
