# Generated by Django 5.2.1 on 2025-05-22 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'firstname',
                    models.CharField(
                        help_text='First name of the person',
                        max_length=120,
                        verbose_name='First name',
                    ),
                ),
                (
                    'lastname',
                    models.CharField(
                        help_text='Last name of the person',
                        max_length=120,
                        verbose_name='Last name',
                    ),
                ),
                (
                    'bio',
                    models.TextField(
                        help_text='Professional biography or summary',
                        verbose_name='Biography',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='created'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='updated'),
                ),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Skill name',
                        max_length=100,
                        unique=True,
                        verbose_name='name',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        help_text='Project title', max_length=200, verbose_name='Title'
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        help_text='Project description', verbose_name='Description'
                    ),
                ),
                (
                    'url',
                    models.URLField(
                        blank=True,
                        help_text='Project URL (optional)',
                        verbose_name='Project URL',
                    ),
                ),
                (
                    'start_date',
                    models.DateField(blank=True, null=True, verbose_name='Start date'),
                ),
                (
                    'end_date',
                    models.DateField(
                        blank=True,
                        help_text='Leave empty if project is ongoing',
                        null=True,
                        verbose_name='End date',
                    ),
                ),
                (
                    'resume',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='projects',
                        to='cvsai.resume',
                        verbose_name='Resume',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSkill',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'level',
                    models.CharField(
                        choices=[
                            ('beginner', 'Beginner'),
                            ('intermediate', 'Intermediate'),
                            ('advanced', 'Advanced'),
                            ('expert', 'Expert'),
                        ],
                        default='intermediate',
                        max_length=20,
                        verbose_name='Skill Level',
                    ),
                ),
                (
                    'resume',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='cvsai.resume'
                    ),
                ),
                (
                    'skill',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='cvsai.skill'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Resume Skill',
                'verbose_name_plural': 'Resume Skills',
                'ordering': ['skill__name'],
                'unique_together': {('resume', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(
                blank=True,
                help_text='Skills with proficiency levels',
                through='cvsai.ResumeSkill',
                to='cvsai.skill',
                verbose_name='Skills',
            ),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'contact_type',
                    models.CharField(
                        choices=[
                            ('email', 'Email'),
                            ('phone', 'Phone'),
                            ('linkedin', 'LinkedIn'),
                            ('github', 'GitHub'),
                            ('website', 'Website'),
                            ('telegram', 'Telegram'),
                            ('skype', 'Skype'),
                            ('other', 'Other'),
                        ],
                        max_length=20,
                        verbose_name='Contact Type',
                    ),
                ),
                (
                    'value',
                    models.CharField(
                        help_text='Contact value (email, phone number, URL, etc.)',
                        max_length=200,
                        verbose_name='Contact Value',
                    ),
                ),
                (
                    'resume',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='contacts',
                        to='cvsai.resume',
                        verbose_name='Resume',
                    ),
                ),
            ],
            options={
                'ordering': ['resume', 'contact_type'],
                'unique_together': {('resume', 'contact_type', 'value')},
            },
        ),
    ]
