# Generated by Django 5.2.1 on 2025-05-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvsai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(
                blank=True,
                help_text='Professional title or position',
                max_length=300,
                verbose_name='Job Title',
            ),
        ),
    ]
