# Generated by Django 5.2.1 on 2025-05-23 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'timestamp',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='When the request was made',
                        verbose_name='Timestamp',
                    ),
                ),
                (
                    'method',
                    models.CharField(
                        help_text='HTTP method (GET, POST, PUT, etc.)',
                        max_length=10,
                        verbose_name='HTTP Method',
                    ),
                ),
                (
                    'path',
                    models.CharField(
                        help_text='Request path', max_length=1024, verbose_name='Path'
                    ),
                ),
                (
                    'query_string',
                    models.TextField(
                        blank=True,
                        help_text='URL query parameters',
                        verbose_name='Query String',
                    ),
                ),
                (
                    'remote_ip',
                    models.GenericIPAddressField(
                        blank=True,
                        help_text='Client IP address',
                        null=True,
                        verbose_name='Remote IP',
                    ),
                ),
                (
                    'user_agent',
                    models.TextField(
                        blank=True,
                        help_text='Browser/client information',
                        verbose_name='User Agent',
                    ),
                ),
                (
                    'response_status',
                    models.PositiveIntegerField(
                        blank=True,
                        help_text='HTTP response status code',
                        null=True,
                        verbose_name='Response Status',
                    ),
                ),
                (
                    'response_time_ms',
                    models.PositiveIntegerField(
                        blank=True,
                        help_text='Request processing time in milliseconds',
                        null=True,
                        verbose_name='Response Time (ms)',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        help_text='Authenticated user (if any)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='User',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-timestamp'],
                'indexes': [
                    models.Index(
                        fields=['-timestamp'], name='audit_reque_timesta_478c53_idx'
                    ),
                    models.Index(
                        fields=['method'], name='audit_reque_method_1ac6f2_idx'
                    ),
                    models.Index(fields=['path'], name='audit_reque_path_e5a644_idx'),
                    models.Index(
                        fields=['user'], name='audit_reque_user_id_52d4cd_idx'
                    ),
                ],
            },
        ),
    ]
